name: Atualizar timestamp e fazer deploy

on:
  push:
    branches:
      - main

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Atualizar timestamp
        run: node scripts/update-timestamp.mjs

      - name: Commit e push das alterações
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/lastUpdate.ts
          git diff --cached --quiet || git commit -m "chore: update lastUpdate timestamp [bot]"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

